swagger: '2.0'
info:
  title: sms
  version: '0.1'
consumes:
  - application/json
  - multipart/form-data
produces:
  - application/json
paths:
  /sms/hello:
    get:
      tags:
        - sms
      summary: sms
      operationId: services.hello.hello
      responses:
        '200':
          description: return
          schema:
            type: string